# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
verbatim:
  cabal-version: 3.6
name:       apply-merge
version:    0.0.0.0
github:     "pgujjula/apply-merge"
license:    BSD-3-Clause
author:     "Preetham Gujjula"
maintainer: "libraries@mail.preetham.io"
copyright:  "Preetham Gujjula"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at
  <https://github.com/pgujjula/apply-merge#readme>

# Can't test with ghc-9.8 series because falsify doesn't support it yet.
tested-with: GHC == {9.2.8, 9.4.8, 9.6.4}

ghc-options:
- -Wall
- -Wunused-packages

dependencies:
- base ^>= {4.16, 4.17, 4.18, 4.19}

language: GHC2021

library:
  source-dirs: src
  exposed-modules:
  - Data.List.ApplyMerge
  other-modules:
  - Data.List.ApplyMerge.IntSet
  dependencies:
  - containers ^>= {0.6}
  - pqueue ^>= {1.4, 1.5}

tests:
  apply-merge-tests:
    source-dirs:
    - src
    - test
    main: Main.hs
    other-modules:
    - Data.DoublyLinkedList.STRef
    - Data.List.ApplyMerge
    - Data.List.ApplyMerge.DoublyLinkedList
    - Data.List.ApplyMerge.IntMap
    - Data.List.ApplyMerge.IntSet
    - Data.PQueue.Prio.Min.Mutable
    - Test.Data.DoublyLinkedList.STRef
    - Test.Data.List.ApplyMerge.Common
    - Test.Data.List.ApplyMerge.DoublyLinkedList
    - Test.Data.List.ApplyMerge.IntMap
    - Test.Data.List.ApplyMerge.IntSet
    - Test.Data.PQueue.Prio.Min.Mutable
    dependencies:
    - containers ^>= {0.6}
    - falsify ^>= {0.2}
    - pqueue ^>= {1.4, 1.5}
    - tasty ^>= {1.4, 1.5}
    - tasty-expected-failure ^>= {0.12}
    - tasty-hunit ^>= {0.10}
    - transformers ^>= {0.5, 0.6}
    - vector ^>= {0.12, 0.13}

benchmarks:
  apply-merge-benchmarks:
    source-dirs:
    - src
    - bench
    main: Main.hs
    other-modules:
    - Data.DoublyLinkedList.STRef
    - Data.List.ApplyMerge
    - Data.List.ApplyMerge.DoublyLinkedList
    - Data.List.ApplyMerge.IntMap
    - Data.List.ApplyMerge.IntSet
    - Data.PQueue.Prio.Min.Mutable
    - Bench.Data.DoublyLinkedList.STRef
    - Bench.PriorityQueue.MinPQueue
    - Bench.PriorityQueue.MinPQueue.Mutable
    dependencies:
    - containers ^>= {0.6}
    - pqueue ^>= {1.4, 1.5}
    - tasty-bench ^>= {0.3}
    - transformers ^>= {0.5, 0.6}
    - vector ^>= {0.12, 0.13}
