# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause

name:       apply-merge
version:    0.0.0.0
github:     "pgujjula/apply-merge"
license:    BSD-3-Clause
author:     "Preetham Gujjula"
maintainer: "libraries@mail.preetham.io"
copyright:  "Preetham Gujjula"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at
  <https://github.com/pgujjula/apply-merge#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.16 && < 5

language: GHC2021

library:
  source-dirs: src
  exposed-modules:
  - Data.List.ApplyMerge
  - Data.List.ApplyMerge.IntMap
  - Data.List.ApplyMerge.IntSet
  dependencies:
  - containers
  - mtl
  - optics
  - pqueue

tests:
  apply-merge-tests:
    source-dirs: test
    main: Main.hs
    other-modules:
    - Test.Data.List.ApplyMerge.Common
    - Test.Data.List.ApplyMerge.IntMap
    - Test.Data.List.ApplyMerge.IntSet
    dependencies:
    - apply-merge
    - tasty
    - tasty-hunit

benchmarks:
  apply-merge-benchmarks:
    source-dirs: bench
    main: Main.hs
    dependencies:
    - apply-merge
    - tasty-bench
